name: Generate Tasks Summary on Push

on:
  push:
    branches:
      - 'tasktable'

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yq (Go version)
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Generate Tasks Summary Table
        run: |
          cd lm_eval/tasks
          output_file="tasks_summary.md"
          echo "Task | Group | Output Type | Metadata" > "$output_file"
          echo "--- | --- | --- | ---" >> "$output_file"
          find . -type f -name '*.yaml' | while read -r file; do
              task=$(yq e '.task // "N/A"' "$file")
              group=$(yq e '.group[] // "N/A"' "$file")
              output_type=$(yq e '.output_type // "N/A"' "$file")
              metadata=$(yq e '.metadata | if type=="array" then join(", ") else . // "N/A" end' "$file")
              include_file=$(yq e '.include // null' "$file")
              if [ "$include_file" != "null" ]; then
                  include_path=$(dirname "$file")/"$include_file"
                  if [ -z "$group" ]; then
                      group=$(yq e '.group[] // "N/A"' "$include_path")
                  fi
                  if [ -z "$output_type" ]; then
                      output_type=$(yq e '.output_type // "N/A"' "$include_path")
                  fi
                  if [ -z "$metadata" ]; then
                      metadata=$(yq e '.metadata | if type=="array" then join(", ") else . // "N/A" end' "$include_path")
                  fi
              fi
              echo "$task | $group | $output_type | $metadata" >> "$output_file"
          done

      - name: Add and Commit Changes
        uses: EndBug/add-and-commit@v9
